@startuml AddItem
autoactivate on
skinparam Style strictuml
skinparam shadowing false
actor   Actor   as a
participant "decentralized auction system" as das

a -> das: addItem()
das -> das: Check if item belongs to owner
return status
return response

@enduml