@startuml Recharge
autoactivate on
skinparam Style strictuml
skinparam shadowing false
actor   Actor   as a
participant "decentralized auction system" as das

a -> das: coinCharge(uint, uint)
return response


@enduml