@startuml state
hide empty description
skinparam shadowing false
State PENDING
State START
State STOP

[*] -> PENDING
PENDING -> START: Create auction
START -> STOP: Revoke token
START -> STOP: Revoke auction
START -> STOP: successful transaction
STOP -> [*]
@enduml